### ISSUE TITLE
README for `gcloud/cli` is documenting `gcloud/auth`

### ISSUE THREAD

**Issue by steren** [actions/gcloud#1]
https://github.com/actions/gcloud/blob/master/cli/README.md
and
https://github.com/actions/gcloud/blob/master/auth/README.md
are identical.

This seems to be a mistake.

**Comment by jordanwilson230** [comment]
...crickets

**Comment by hfaulds** [comment]
I just started trying to improve on the documentation of these two actions in https://github.com/actions/gcloud/pull/2. If you have a moment I'd greatly appreciate if you could let me know any feedback you had

**Comment by hfaulds** [comment]
Closing this out now that #2 is in, any feedback on those changes is very welcome
