### ISSUE TITLE
weird error on auth... sometimes

### ISSUE THREAD

**Issue by caarlos0** [actions/gcloud#10]
There is an error that happens randomly for us. It happened 2 times so far, I'm not sure if it is something on the auth action or on actions itself... 

We have this action on our workflow:

```workflow
action "Setup Google Cloud" {
  needs = ["tag filter"]
  uses = "actions/gcloud/auth@master"
  secrets = ["GCLOUD_AUTH"]
}
```

Which sometimes yields this error:

![image](https://user-images.githubusercontent.com/245435/53733648-62fc5f80-3e60-11e9-801b-22af3ad1aef5.png)

Re-running the action without any change works...

Looking into the entrypoint of the auth action, it seems that everything is right...

The only thing I can think of is that the `gcloud` CLI is failing and not throwing any errors to STDOUT/STDERR... Is that possible? If so, maybe add a `echo something` before/after the command to have more info? 

If its not there, maybe an issue with actions itself? I'm not sure how to debug it...

**Comment by caarlos0** [comment]
cc/ @mcolyer maybe 🤔

**Comment by g-harel** [comment]
I'm getting similar errors on both `auth` and `cli`, some extra logs would help a lot with debugging.

**Comment by chrispat** [comment]
This actions has been deprecated in favor of https://github.com/GoogleCloudPlatform/github-actions.  This repo has been archived and will be made private on 12/31/2019
