### ISSUE TITLE
[Help wanted] My secret is always  invalid

### ISSUE THREAD

**Issue by kapik** [actions/gcloud#13]
Hi ! 

I need your help to understand why my secret is always invalid.
I have followed the Readme, the Github documentation for Secret and the Google documentation for GCloud Auth.
I know the flow for generate a JSON key file and I have already use this kind of key on anothers platforms for publish images (eg: Portainer and BuddyWorks).
But my secret seems to be invalid. 
I have the following messages errors: 

```
base64: invalid input
```
or (depends of my JSON key)
```
ERROR: (gcloud.auth.activate-service-account) Could not read json file /github/home/gcloud.json: No JSON object could be decoded
```

I have used the Github Secret feature (like your example).
Thanks for your help 🙏

**Comment by case** [comment]
@kapik were you able to resolve this somehow?

**Comment by case** [comment]
Fwiw, using the output of `$ base64 {gcloud-credentials.json}` as `GCLOUD_AUTH` worked, rather than using the json contents as the auth secret.
