### ISSUE TITLE
Same repo, different service accounts (hence, multiple GCLOUD_AUTH env)

### ISSUE THREAD

**Issue by emdotem** [actions/gcloud#16]
Hello,
I have two branches, staging/master and we use two different service account to auth against the staging/production environment.

By default `gcloud/auth` should read from `GCLOUD_AUTH` env variable but it should also possible to specify one, for instance: `GCLOUD_AUTH_STAGING`.

How can be accomplished?

**Comment by jordankid93** [comment]
Not sure if you ever figured this out but I _think_ you would have to either A) create _another_ step that auth's with the `GCLOUD_AUTH` set to your other value or B) create a different workflows to handle staging/production

**Comment by chrispat** [comment]
This actions has been deprecated in favor of https://github.com/GoogleCloudPlatform/github-actions.  This repo has been archived and will be made private on 12/31/2019
