### ISSUE TITLE
docs: deprecated syntax in README

### ISSUE THREAD

**Issue by jmhodges** [actions/gcloud#23]
The readmes for [auth](https://github.com/actions/gcloud/blob/master/auth/README.md) and [cli]( https://github.com/actions/gcloud/blob/master/cli/README.md) both use the deprecated workflow syntax instead of YAML. It'd be nice to see those updated.

**Comment by adyavanapalli** [comment]
I created a [PR](https://github.com/actions/gcloud/pull/20) for this, but no one has said anything in over 3 weeks.

**Comment by chrispat** [comment]
This actions has been deprecated in favor of https://github.com/GoogleCloudPlatform/github-actions.  This repo has been archived and will be made private on 12/31/2019
