### ISSUE TITLE
docs: secrets doc link in auth README

### ISSUE THREAD

**Issue by jmhodges** [actions/gcloud#24]
The auth README links to a page that seems to no longer exist in "For information about using Secrets in Actions please see the Actions docs."

The link in "Actions docs" redirects to a Actions documentation landing page and it's unclear where to go to find the secrets documentation

**Comment by chrispat** [comment]
This actions has been deprecated in favor of https://github.com/GoogleCloudPlatform/github-actions.  This repo has been archived and will be made private on 12/31/2019
