### ISSUE TITLE
Build and deploy broken due to actions/action-builder/shell being gone

### ISSUE THREAD

**Issue by richardkazuomiller** [actions/gcloud#26]
Since the `actions/action-builder` appears to have been deleted, this action is no longer being deployed to Docker Hub. I don't know what `actions/action-builder/shell` was meant to do, but if there is an alternative that can easily be swapped in, it would be great so this action could be included as a Docker image instead of cloned

**Comment by richardkazuomiller** [comment]
Example: <https://github.com/actions/gcloud/commit/32e17fef6c79fec6c20def6227c38de66e60737a/checks?check_suite_id=298603350>

**Comment by chrispat** [comment]
This actions has been deprecated in favor of https://github.com/GoogleCloudPlatform/github-actions.  This repo has been archived and will be made private on 12/31/2019
