### ISSUE TITLE
Auth Secrets

### ISSUE THREAD

**Issue by vsoch** [actions/gcloud#4]
hey Google Cloud! I'm wondering about the okay-ness of saving a base64 encoded account token as a secret when it's [not recommended](https://developer.github.com/actions/creating-workflows/storing-secrets/) to store production secrets while GitHub actions are in beta. Did you see this?

**Comment by mcolyer** [comment]
> hey Google Cloud! I'm wondering about the okay-ness of saving a base64 encoded account token as a secret when it's [not recommended](https://developer.github.com/actions/creating-workflows/storing-secrets/) to store production secrets while GitHub actions are in beta. Did you see this?

@vsoch I work for GitHub (not Google) and we recommend using GitHub actions on non-production workflows or low risk production workflows while the product is in beta. Does that help?

**Comment by vsoch** [comment]
hey @mcolyer, definitely! Can we distinguish between production / non-production and security level? For example, I might use an API token that should be absolutely secure for a non production workflow. If there is any chance that the key could be compromised given that GitHub actions is in beta, then I wouldn't want to use it (even if it's for non production testing.)

When do you (approximately) estimate actions might go out of beta, and more specifically, it will be okay to include environment variable secrets?

**Comment by mcolyer** [comment]
> If there is any chance that the key could be compromised given that GitHub actions is in beta, then I wouldn't want to use it (even if it's for non production testing.)

Yep, so that's exactly the kind of thing I would discourage you from adding for now.

> When do you (approximately) estimate actions might go out of beta, and more specifically, it will be okay to include environment variable secrets?

I don't have anything more I can share at the moment but the intent is that when it is generally available that it will be safe to store the secure tokens you mentioned above. We're being extra cautious here because we want to make sure we get this right.

**Comment by vsoch** [comment]
okay great! Thanks for the clarification, and I'm really looking forward to when actions are generally available. They are seriously awesome, and I 100% support erring on the side of cautiousness.

Closing issue! Thanks again.
